# Generated by Django 5.0.9 on 2024-11-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0002_server_extension_server_queue_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='extension',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='server',
        ),
        migrations.AddField(
            model_name='extension',
            name='leadvertex_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='queues',
            field=models.ManyToManyField(blank=True, related_name='extensions', to='pbx.queue'),
        ),
    ]
