# Generated by Django 5.0.9 on 2024-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='calls',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
