# Generated by Django 5.0.9 on 2024-11-24 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_order_calls'),
        ('pbx', '0003_dialstatus_remove_extension_queue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dial_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pbx.dialstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pbx.extension'),
        ),
    ]
